authorName: Itay_Levinas
experimentName: fine_tuning_Clique_GCN
trialConcurrency: 2 # max GPUs to use simultaneously.
maxExecDuration: 7h
maxTrialNum: 4000
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space_undirected.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: minimize
trial:
  command: python nni_experiment.py -n 500 -cs 20
  codeDir: .
  gpuNum: 1
localConfig:
  maxTrialNumPerGpu: 2
  useActiveGpu: true
